### ISSUE TITLE
Channel names

### ISSUE THREAD

**Issue by Steph-Fulda** [CSC-UW/csc-eeg-tools#18]
Hi Armand,

first: great tool! I am only just getting started but am impressed how fast the plotter is. I have just a quick question - I have seen that the specified montages are in some .emo format I am not familiar with. Is there a way for me to specify different montages outside the plotter window? And maybe save them in the montages folder so that they are available?
Also I thought I read somewhere - but really not recall where and might be totally mistaken - that there was the possibility to manipulate (filter/amplitude) channels differently, i.e. have channels with different filters and amplitudes. I searched around but could not find any information whether and how this is already possible.
Thanks a lot and with kind regards
Steph

**Comment by Mensen** [comment]
Hi Steph,

Yes, this .emo file is actually just a mat file with a different file extension so I can search for them easier. You can load them as a mat file `(load('filename', '-mat')` and create them on your own and then save the format.

As for amplitude you can just change the "scale" property in the montage settings.

Filters are a little trickier. Applying a single filter setting to all channels is very quickly done. Applying unique filters to each channel is slower and would slow down scrolling and plotting etc. I am working on something for this though as I do all my sleep scoring in the csc_eeg_plotter and having different filter settings for EOG, EEG and EMG is quite helpful.

I can let you know when this feature is implemented but I won't get around to it for a couple weeks at least.

**Comment by Steph-Fulda** [comment]
Thanks much, Armand! That is very helpful. It would be great if you could keep me in the loop re the possibility to adjust filters for different channels.

**Comment by Mensen** [comment]
So I managed to implement the filtering options in the newest release.
Its not well documented yet (nothing really is), but you can select channel types from the montage list, and also set their individual filter properties from the options -> filter settings box.

**Comment by Steph-Fulda** [comment]
Just tried it, works great! Thanks so much!
